#
# docker run --rm -it -d -p ${HTTP_PORT}:80 -p ${HTTPS_PORT}:443 -e ASPNETCORE_URLS="https://+;http://+" -e ASPNETCORE_HTTPS_PORT=${HTTPS_PORT} -e ASPNETCORE_Kestrel__Certificates__Default__Password="!qazxsw2" -e ASPNETCORE_Kestrel__Certificates__Default__Path=/https/diaryoftraderwebapi.pfx -v ${HOME}/.aspnet/https:/https/ --name DiaryOfTrader.WebApi diaryoftraderwebapi
#
version: "3.9"
services:
  diaryoftraderwebapi:
    image: diaryoftraderwebapi
    build:
      context: .
      dockerfile: Dockerfile.WinApi
    container_name: DiaryOfTrader.WebApi
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https/
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=${HTTPS_PORT}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${Certificates__Default__Password}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/${Certificates__Default__Path}
    logging:
      options:
        max-size: '5m'
        max-file: '10'
    restart: always
    depends_on:
      - redis
      - pg
    networks:
      - diaryoftrader

  redis:
    image: redis/redis-stack
    container_name: redis
    ports:
      - 8001:8001
      - 6379:6379
    logging:
      options:
        max-size: '5m'
        max-file: '10'
    networks:
      - diaryoftrader

  pg:
    container_name: pg
    image: postgres:16.0
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ${PGDATA}:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    logging:
      options:
        max-size: '5m'
        max-file: '10'
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - diaryoftrader

networks:
  diaryoftrader:
    name: diaryoftrader
    driver: bridge
