//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiaryOfTrader.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiaryOfTrader.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чикаго.
        /// </summary>
        internal static string Chicago {
            get {
                return ResourceManager.GetString("Chicago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чикаго (CHX) – третья крупнейшая биржевая площадка в США и самая мощная по объему торгов за пределами Нью-Йорка.
        ///Фьючерсы на биткойны (BTC) и Ethereum (ETH) теперь торгуются на Чикагской бирже. Обе эти криптовалюты доступны как фьючерсные позиции..
        /// </summary>
        internal static string ChicagoDesc {
            get {
                return ResourceManager.GetString("ChicagoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сделка.
        /// </summary>
        internal static string Diary {
            get {
                return ResourceManager.GetString("Diary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binance.
        /// </summary>
        internal static string ExchangeBinance {
            get {
                return ResourceManager.GetString("ExchangeBinance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Криптовалютная биржа Binance.
        /// </summary>
        internal static string ExchangeBinanceDesc {
            get {
                return ResourceManager.GetString("ExchangeBinanceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forex.
        /// </summary>
        internal static string ExchangeForex {
            get {
                return ResourceManager.GetString("ExchangeForex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форекс – международный финансовый рынок, на котором происходит обмен валют.
        /// </summary>
        internal static string ExchangeForexDesc {
            get {
                return ResourceManager.GetString("ExchangeForexDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Франкфурт.
        /// </summary>
        internal static string Frankfurt {
            get {
                return ResourceManager.GetString("Frankfurt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Франкфурт (FSE) 
        ///Именно на Немецкой бирже одни из самых высоких показателей по уровню прибыли, выручки и капитализации в Европе. Все операции на бирже проходят в электронной системе торгов Xetra – в ней ведут работу более 650 клиентов биржи, включая около 5-ти тысяч трейдеров и 270 банков со всего мира..
        /// </summary>
        internal static string FrankfurtDesc {
            get {
                return ResourceManager.GetString("FrankfurtDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гонконг.
        /// </summary>
        internal static string HongKong {
            get {
                return ResourceManager.GetString("HongKong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гонконг (HKEX)
        ///Гонконгская фондовая биржа работает с 4:00 до 12:00 по московскому времени. Открытие торгов может начаться в 4: 15 и в 4: 20 (МСК)..
        /// </summary>
        internal static string HongKongDesc {
            get {
                return ResourceManager.GetString("HongKongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лондон.
        /// </summary>
        internal static string London {
            get {
                return ResourceManager.GetString("London", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лондон (LSE) 
        ///Основной центр торговли – Лондонская биржа начинает свою работу  в 10:00(МСК). Европейская сессия пересекается сразу с двумя другими сессиями: с азиатской с начала и до 11:00 по МСК, и с американской с 16:30 до конца сессии. Во время пересечений данных сессий волатильность пересекающихся валютных пар данных регионов возрастает крайне значительно, что делает данные периоды крайне опасными для новичков.
        ///По торговому обороту LSE забирает на себя около 50% международной торговли акциями. на Лонд [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LondonDesc {
            get {
                return ResourceManager.GetString("LondonDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обзор рынка.
        /// </summary>
        internal static string MarketReview {
            get {
                return ResourceManager.GetString("MarketReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нью-Йорк.
        /// </summary>
        internal static string NewYork {
            get {
                return ResourceManager.GetString("NewYork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нью Йорк (NYSE)   Наиболее оживленное время торговли на бирже Форекс начинается в тот момент, когда в рынок входит Нью-Йоркская торговая площадка.
        ///Биржа открыта в будни – с понедельника по пятницу – и работает с 9:30 до 16:00 по Нью-Йоркскому времени. Разница с Москвой — 7 часов..
        /// </summary>
        internal static string NewYorkDesc {
            get {
                return ResourceManager.GetString("NewYorkDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сидней.
        /// </summary>
        internal static string Sydney {
            get {
                return ResourceManager.GetString("Sydney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сидней (ASX)
        ///Расположенная в Сиднее Австралийская Фондовая Биржа (ASX) является более крупной, чем Новозеландская. Спустя час, после открытия бирж Новой Зеландии  к ним подключаются австралийские биржи. Окончание торгов происходит в 9 часов (МСК)..
        /// </summary>
        internal static string SydneyDesc {
            get {
                return ResourceManager.GetString("SydneyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инструмент.
        /// </summary>
        internal static string Symbol {
            get {
                return ResourceManager.GetString("Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BNBUSD.
        /// </summary>
        internal static string SymbolBNBUSD {
            get {
                return ResourceManager.GetString("SymbolBNBUSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курс BNB (Binance Coin) к Доллару США.
        /// </summary>
        internal static string SymbolBNBUSDDesc {
            get {
                return ResourceManager.GetString("SymbolBNBUSDDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTCUSD.
        /// </summary>
        internal static string SymbolBTCUSD {
            get {
                return ResourceManager.GetString("SymbolBTCUSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTC/USD – это инновационная валютная пара нового поколения, в которой отражается соотношение котировки одного биткоина к доллару США..
        /// </summary>
        internal static string SymbolBTCUSDDesc {
            get {
                return ResourceManager.GetString("SymbolBTCUSDDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXY.
        /// </summary>
        internal static string SymbolDXY {
            get {
                return ResourceManager.GetString("SymbolDXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обозначение Индекса доллара — DXY. Индекс доллара передает ценность валюты Америки. Данный показатель представлен в виде соотношения шести крупных валют с USD. В корзину включены — евро (EUR), йена (JPY), фунт стерлингов (GBP), канадский доллар (CAD), шведская крона (SEK), швейцарский франк (CHF)..
        /// </summary>
        internal static string SymbolDXYDesc {
            get {
                return ResourceManager.GetString("SymbolDXYDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETHUSD.
        /// </summary>
        internal static string SymbolETHUSD {
            get {
                return ResourceManager.GetString("SymbolETHUSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курс Эфира (эфириума) к Доллару США.
        /// </summary>
        internal static string SymbolETHUSDDesc {
            get {
                return ResourceManager.GetString("SymbolETHUSDDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EURUSD.
        /// </summary>
        internal static string SymbolEURUSD {
            get {
                return ResourceManager.GetString("SymbolEURUSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EURUSD - валютная пара, которая имеет достаточно низкий спред и показывает соотношение евро и доллара США. В паре евро выступает как базовая валюта, а доллар США - как котируемая.
        /// </summary>
        internal static string SymbolEURUSDDesc {
            get {
                return ResourceManager.GetString("SymbolEURUSDDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRBUSD.
        /// </summary>
        internal static string SymbolGRBUSD {
            get {
                return ResourceManager.GetString("SymbolGRBUSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SymbolGRBUSDDesc {
            get {
                return ResourceManager.GetString("SymbolGRBUSDDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPX.
        /// </summary>
        internal static string SymbolSPX {
            get {
                return ResourceManager.GetString("SymbolSPX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPX – это индекс S&amp;P500, который был впервые составлен Standard&amp;Poor`s еще в 1923 году. Это взвешенный по рыночной капитализации индекс, в который входят акции 500 самых крупных компаний США.
        /// </summary>
        internal static string SymbolSPXDesc {
            get {
                return ResourceManager.GetString("SymbolSPXDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USDJPY.
        /// </summary>
        internal static string SymbolUSDJPY {
            get {
                return ResourceManager.GetString("SymbolUSDJPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USDJPY — это валютная пара, в которую входит доллар США и японская иена. Эту пару называют «иена» или «гофер». Она является второй по объёму торговой парой на рынке Форекс..
        /// </summary>
        internal static string SymbolUSDJPYDesc {
            get {
                return ResourceManager.GetString("SymbolUSDJPYDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тайм Фрейм.
        /// </summary>
        internal static string TimeFrame {
            get {
                return ResourceManager.GetString("TimeFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D1.
        /// </summary>
        internal static string TimeFrameD1 {
            get {
                return ResourceManager.GetString("TimeFrameD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дневной.
        /// </summary>
        internal static string TimeFrameD1Desc {
            get {
                return ResourceManager.GetString("TimeFrameD1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1.
        /// </summary>
        internal static string TimeFrameH1 {
            get {
                return ResourceManager.GetString("TimeFrameH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Часовой.
        /// </summary>
        internal static string TimeFrameH1Desc {
            get {
                return ResourceManager.GetString("TimeFrameH1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H4.
        /// </summary>
        internal static string TimeFrameH4 {
            get {
                return ResourceManager.GetString("TimeFrameH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Четырех часовой.
        /// </summary>
        internal static string TimeFrameH4Desc {
            get {
                return ResourceManager.GetString("TimeFrameH4Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M1.
        /// </summary>
        internal static string TimeFrameM1 {
            get {
                return ResourceManager.GetString("TimeFrameM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M15.
        /// </summary>
        internal static string TimeFrameM15 {
            get {
                return ResourceManager.GetString("TimeFrameM15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пятнадцати минутный.
        /// </summary>
        internal static string TimeFrameM15Desc {
            get {
                return ResourceManager.GetString("TimeFrameM15Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минутный тренд.
        /// </summary>
        internal static string TimeFrameM1Desc {
            get {
                return ResourceManager.GetString("TimeFrameM1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M30.
        /// </summary>
        internal static string TimeFrameM30 {
            get {
                return ResourceManager.GetString("TimeFrameM30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тридцати минутный.
        /// </summary>
        internal static string TimeFrameM30Desc {
            get {
                return ResourceManager.GetString("TimeFrameM30Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M5.
        /// </summary>
        internal static string TimeFrameM5 {
            get {
                return ResourceManager.GetString("TimeFrameM5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пятиминутный.
        /// </summary>
        internal static string TimeFrameM5Desc {
            get {
                return ResourceManager.GetString("TimeFrameM5Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MN.
        /// </summary>
        internal static string TimeFrameMN {
            get {
                return ResourceManager.GetString("TimeFrameMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Месячный.
        /// </summary>
        internal static string TimeFrameMNDesc {
            get {
                return ResourceManager.GetString("TimeFrameMNDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W1.
        /// </summary>
        internal static string TimeFrameW1 {
            get {
                return ResourceManager.GetString("TimeFrameW1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недельный.
        /// </summary>
        internal static string TimeFrameW1Desc {
            get {
                return ResourceManager.GetString("TimeFrameW1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Токио.
        /// </summary>
        internal static string Tokyo {
            get {
                return ResourceManager.GetString("Tokyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Токио (TSE)
        ///В Азиатском же регионе TSE является самой востребованной биржей: более 80% сделок осуществляется именно здесь.
        ///Трейдер, подав заявление на рассмотрение его для участия на бирже, может ожидать несколько месяцев, прежде чем биржевая комиссия выдаст ему соответствующий допуск. Биржа, при этом, имеет право запрашивать данные о кандидатуре в участники TSE. Такие требования связаны с обеспечением стабильности на рынке и безопасностью..
        /// </summary>
        internal static string TokyoDesc {
            get {
                return ResourceManager.GetString("TokyoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Биржа.
        /// </summary>
        internal static string TraderExchange {
            get {
                return ResourceManager.GetString("TraderExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регион.
        /// </summary>
        internal static string TraderRegion {
            get {
                return ResourceManager.GetString("TraderRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Американский.
        /// </summary>
        internal static string TraderRegionAmerica {
            get {
                return ResourceManager.GetString("TraderRegionAmerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наибольшие объемы торгов приходятся на первые два часа американской сессии, когда одновременно торгуют Нью-Йорк и Лондон. Начало по МСК данного периода приходится на 16:00, а окончание на 18:00, когда закрываются торги в Лондоне.
        ///Также в пятницу вечером американские трейдеры предпочитают зафиксировать прибыль перед выходными и по основным тенденциям может наблюдаться откат.
        /// Американская сессия считается наиболее агрессивной. Следует помнить, что перед открытием бирж в Чикаго и Нью-Йорке трейдерам стоит о [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TraderRegionAmericaDesc {
            get {
                return ResourceManager.GetString("TraderRegionAmericaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Азиатский.
        /// </summary>
        internal static string TraderRegionAsia {
            get {
                return ResourceManager.GetString("TraderRegionAsia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Азиатская торговая сессия характеризуется довольно низкой волатильностью. Открытие торгов азиатской сессии происходит в 3:00 по Москве, закрытие – в 12:00. Торги на фондовом рынке проходят во все дни, кроме выходных (субботы и воскресенья), а также праздничных дней, которые биржа объявляет заранее.
        ///Азиатские трейдеры часто задают тренды всему торговому дню. Новое формирование трендов, может складываться из новостей, вышедших в выходные.
        ///Своего торгового пика рынок Азии достигает в 08:00 по Москве с открыт [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TraderRegionAsiaDesc {
            get {
                return ResourceManager.GetString("TraderRegionAsiaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Европейский.
        /// </summary>
        internal static string TraderRegionEurope {
            get {
                return ResourceManager.GetString("TraderRegionEurope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пик активности выпадает на период с 17,30 до 18,00, перед закрытием европейской сессии. В этот момент многие игроки стараются выжать из рынка как можно больше и успеть закрыть позиции без переноса на следующий день.
        /// </summary>
        internal static string TraderRegionEuropeDesc {
            get {
                return ResourceManager.GetString("TraderRegionEuropeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тихоокенский.
        /// </summary>
        internal static string TraderRegionPacific {
            get {
                return ResourceManager.GetString("TraderRegionPacific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тихоокеанская торговая сессия длится с 0:00 до 9:00 по Московскому времени.
        ///Начало работы Тихоокеанской торговой сессии совпадает с окончанием работы американской и знаменует собой начало нового торгового дня.
        ///Главной особенностью Тихоокеанской сессии (Pacific Session) является период затишья, когда Американская сессия уже завершилась, а Азиатская еще не начала свою работу. Подавляющая часть опытных трейдеров и крупные игроки в начале Тихоокеанской сессии берут тайм-аут и дожидаются выхода на рынок азиатс [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TraderRegionPacificDesc {
            get {
                return ResourceManager.GetString("TraderRegionPacificDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат сделки.
        /// </summary>
        internal static string TraderResult {
            get {
                return ResourceManager.GetString("TraderResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трейдинг закончился потерей ликвидности.
        /// </summary>
        internal static string TraderResultDescriptionLoss {
            get {
                return ResourceManager.GetString("TraderResultDescriptionLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трейдинг не состоялся.
        /// </summary>
        internal static string TraderResultDescriptionNone {
            get {
                return ResourceManager.GetString("TraderResultDescriptionNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трейдинг закончился с прибылью.
        /// </summary>
        internal static string TraderResultDescriptionSuccess {
            get {
                return ResourceManager.GetString("TraderResultDescriptionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потеря.
        /// </summary>
        internal static string TraderResultLoss {
            get {
                return ResourceManager.GetString("TraderResultLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без результата.
        /// </summary>
        internal static string TraderResultNone {
            get {
                return ResourceManager.GetString("TraderResultNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успех.
        /// </summary>
        internal static string TraderResultSuccess {
            get {
                return ResourceManager.GetString("TraderResultSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Торговая сессия.
        /// </summary>
        internal static string TraderSession {
            get {
                return ResourceManager.GetString("TraderSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тренд.
        /// </summary>
        internal static string Trend {
            get {
                return ResourceManager.GetString("Trend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нисходящий(медвежий).
        /// </summary>
        internal static string TrendDownward {
            get {
                return ResourceManager.GetString("TrendDownward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тренд в котором каждый последующий хай ниже предыдущего..
        /// </summary>
        internal static string TrendDownwardDesc {
            get {
                return ResourceManager.GetString("TrendDownwardDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Боковой.
        /// </summary>
        internal static string TrendSide {
            get {
                return ResourceManager.GetString("TrendSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тренд, при котором последующие хаи или лои находятся на одном уровне.
        /// </summary>
        internal static string TrendSideDesc {
            get {
                return ResourceManager.GetString("TrendSideDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восходящий(бычий).
        /// </summary>
        internal static string TrendUpward {
            get {
                return ResourceManager.GetString("TrendUpward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тренд в котором каждый последующий лой выше предыдущего.
        /// </summary>
        internal static string TrendUpwardDesc {
            get {
                return ResourceManager.GetString("TrendUpwardDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип кошелька.
        /// </summary>
        internal static string Wallet {
            get {
                return ResourceManager.GetString("Wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Демо.
        /// </summary>
        internal static string WalletDemo {
            get {
                return ResourceManager.GetString("WalletDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Демо кошелек.
        /// </summary>
        internal static string WalletDemoDesc {
            get {
                return ResourceManager.GetString("WalletDemoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Симулятор.
        /// </summary>
        internal static string WalletMarketSimulator {
            get {
                return ResourceManager.GetString("WalletMarketSimulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Используется на симуляторах рынка.
        /// </summary>
        internal static string WalletMarketSimulatorDesc {
            get {
                return ResourceManager.GetString("WalletMarketSimulatorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Торговый.
        /// </summary>
        internal static string WalletReal {
            get {
                return ResourceManager.GetString("WalletReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реальный кошелек с ликвидностью.
        /// </summary>
        internal static string WalletRealDesc {
            get {
                return ResourceManager.GetString("WalletRealDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Веллингтон.
        /// </summary>
        internal static string Wellington {
            get {
                return ResourceManager.GetString("Wellington", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В 0:00 по Москве стартуют новозеландские биржи, в частности Новозеландская Фондовая Биржа (NZX)..
        /// </summary>
        internal static string WellingtonDesc {
            get {
                return ResourceManager.GetString("WellingtonDesc", resourceCulture);
            }
        }
    }
}
