// <auto-generated />
using System;
using DiaryOfTrader.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DiaryOfTrader.Core.Migrations
{
    [DbContext(typeof(DiaryOfTraderCtx))]
    partial class DiaryOfTraderCtxModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("DiarySequence");

            modelBuilder.HasSequence("EconomicEventSequence");

            modelBuilder.HasSequence("EconomicScheduleSequence");

            modelBuilder.HasSequence("MarketReviewSequence");

            modelBuilder.HasSequence("MarketReviewTimeFrameSequence");

            modelBuilder.HasSequence("ScreenShotSequence");

            modelBuilder.HasSequence("SymbolSequence");

            modelBuilder.HasSequence("TimeFrameSequence");

            modelBuilder.HasSequence("TraderExchangeSequence");

            modelBuilder.HasSequence("TraderRegionSequence");

            modelBuilder.HasSequence("TraderResultSequence");

            modelBuilder.HasSequence("TraderSequence");

            modelBuilder.HasSequence("TraderSessionSequence");

            modelBuilder.HasSequence("TradingStrategySequence");

            modelBuilder.HasSequence("TrendSequence");

            modelBuilder.HasSequence("WalletSequence");

            modelBuilder.Entity("DiaryOfTrader.Core.Entity.Diary", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"DiarySequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<long>("ID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Deal")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Emotions")
                        .HasColumnType("text");

                    b.Property<long>("EnteredID")
                        .HasColumnType("bigint");

                    b.Property<long?>("ExchangeID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("FinishedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("ReviewID")
                        .HasColumnType("bigint");

                    b.Property<long?>("SessionID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SymbolID")
                        .HasColumnType("bigint");

                    b.Property<long?>("TraderID")
                        .HasColumnType("bigint");

                    b.Property<long>("TraderResultID")
                        .HasColumnType("bigint");

                    b.Property<long>("WalletID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("EnteredID");

                    b.HasIndex("ExchangeID");

                    b.HasIndex("ReviewID");

                    b.HasIndex("SessionID");

                    b.HasIndex("SymbolID");

                    b.HasIndex("TraderID");

                    b.HasIndex("TraderResultID");

                    b.HasIndex("WalletID");

                    b.ToTable("Diary");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("DiaryOfTrader.Core.Entity.Economic.EconomicEvent", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"EconomicEventSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<long>("ID"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocalRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("EconomicEvent");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("DiaryOfTrader.Core.Entity.Economic.EconomicSchedule", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"EconomicScheduleSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<long>("ID"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("DiaryID")
                        .HasColumnType("bigint");

                    b.Property<long?>("EventID")
                        .HasColumnType("bigint");

                    b.Property<string>("Factual")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Importance")
                        .HasColumnType("integer");

                    b.Property<string>("Last")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Previous")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prognosis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.HasIndex("DiaryID");

                    b.HasIndex("EventID");

                    b.ToTable("EconomicSchedule");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("DiaryOfTrader.Core.Entity.MarketReview", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"MarketReviewSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<long>("ID"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long>("ExchangeID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SymbolID")
                        .HasColumnType("bigint");

                    b.Property<long?>("TraderID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("ExchangeID");

                    b.HasIndex("SymbolID");

                    b.HasIndex("TraderID");

                    b.ToTable("MarketReview");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("DiaryOfTrader.Core.Entity.MarketReviewTimeFrame", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"MarketReviewTimeFrameSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<long>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long>("FrameID")
                        .HasColumnType("bigint");

                    b.Property<long>("MarketID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<long?>("ScreenShotID")
                        .HasColumnType("bigint");

                    b.Property<long?>("TrendID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("FrameID");

                    b.HasIndex("MarketID");

                    b.HasIndex("ScreenShotID");

                    b.HasIndex("TrendID");

                    b.ToTable("MarketReviewTimeFrame");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("DiaryOfTrader.Core.Entity.ScreenShot", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"ScreenShotSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<long>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long?>("DiaryID")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("DiaryID");

                    b.ToTable("ScreenShot");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("DiaryOfTrader.Core.Entity.Symbol", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"SymbolSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<long>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Symbol");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("DiaryOfTrader.Core.Entity.TimeFrame", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"TimeFrameSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<long>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Frame");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("DiaryOfTrader.Core.Entity.Trader", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"TraderSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<long>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Trader");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("DiaryOfTrader.Core.Entity.TraderExchange", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"TraderExchangeSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<long>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Exchange");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("DiaryOfTrader.Core.Entity.TraderRegion", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"TraderRegionSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<long>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Region");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("DiaryOfTrader.Core.Entity.TraderResult", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"TraderResultSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<long>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Result");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("DiaryOfTrader.Core.Entity.TraderSession", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"TraderSessionSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<long>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<long>("RegionID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SummerFinished")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SummerStarting")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("WinterFinished")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("WinterStarting")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.HasIndex("RegionID");

                    b.ToTable("Session");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("DiaryOfTrader.Core.Entity.TradingStrategy", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"TradingStrategySequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<long>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("TradingStrategy");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("DiaryOfTrader.Core.Entity.Trend", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"TrendSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<long>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Trend");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("DiaryOfTrader.Core.Entity.Wallet", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"WalletSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<long>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Wallet");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("SymbolTraderExchange", b =>
                {
                    b.Property<long>("ExchangesID")
                        .HasColumnType("bigint");

                    b.Property<long>("SymbolsID")
                        .HasColumnType("bigint");

                    b.HasKey("ExchangesID", "SymbolsID");

                    b.HasIndex("SymbolsID");

                    b.ToTable("ExchangeSymbol", (string)null);
                });

            modelBuilder.Entity("DiaryOfTrader.Core.Entity.Diary", b =>
                {
                    b.HasOne("DiaryOfTrader.Core.Entity.TimeFrame", "Entered")
                        .WithMany()
                        .HasForeignKey("EnteredID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaryOfTrader.Core.Entity.TraderExchange", "Exchange")
                        .WithMany()
                        .HasForeignKey("ExchangeID");

                    b.HasOne("DiaryOfTrader.Core.Entity.MarketReview", "Review")
                        .WithMany()
                        .HasForeignKey("ReviewID");

                    b.HasOne("DiaryOfTrader.Core.Entity.TraderSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionID");

                    b.HasOne("DiaryOfTrader.Core.Entity.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaryOfTrader.Core.Entity.Trader", "Trader")
                        .WithMany()
                        .HasForeignKey("TraderID");

                    b.HasOne("DiaryOfTrader.Core.Entity.TraderResult", "TraderResult")
                        .WithMany()
                        .HasForeignKey("TraderResultID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaryOfTrader.Core.Entity.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entered");

                    b.Navigation("Exchange");

                    b.Navigation("Review");

                    b.Navigation("Session");

                    b.Navigation("Symbol");

                    b.Navigation("Trader");

                    b.Navigation("TraderResult");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("DiaryOfTrader.Core.Entity.Economic.EconomicSchedule", b =>
                {
                    b.HasOne("DiaryOfTrader.Core.Entity.Diary", null)
                        .WithMany("Events")
                        .HasForeignKey("DiaryID");

                    b.HasOne("DiaryOfTrader.Core.Entity.Economic.EconomicEvent", "Event")
                        .WithMany()
                        .HasForeignKey("EventID");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("DiaryOfTrader.Core.Entity.MarketReview", b =>
                {
                    b.HasOne("DiaryOfTrader.Core.Entity.TraderExchange", "Exchange")
                        .WithMany()
                        .HasForeignKey("ExchangeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaryOfTrader.Core.Entity.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaryOfTrader.Core.Entity.Trader", "Trader")
                        .WithMany()
                        .HasForeignKey("TraderID");

                    b.Navigation("Exchange");

                    b.Navigation("Symbol");

                    b.Navigation("Trader");
                });

            modelBuilder.Entity("DiaryOfTrader.Core.Entity.MarketReviewTimeFrame", b =>
                {
                    b.HasOne("DiaryOfTrader.Core.Entity.TimeFrame", "Frame")
                        .WithMany()
                        .HasForeignKey("FrameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaryOfTrader.Core.Entity.MarketReview", "Market")
                        .WithMany("Frames")
                        .HasForeignKey("MarketID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaryOfTrader.Core.Entity.ScreenShot", "ScreenShot")
                        .WithMany()
                        .HasForeignKey("ScreenShotID");

                    b.HasOne("DiaryOfTrader.Core.Entity.Trend", "Trend")
                        .WithMany()
                        .HasForeignKey("TrendID");

                    b.Navigation("Frame");

                    b.Navigation("Market");

                    b.Navigation("ScreenShot");

                    b.Navigation("Trend");
                });

            modelBuilder.Entity("DiaryOfTrader.Core.Entity.ScreenShot", b =>
                {
                    b.HasOne("DiaryOfTrader.Core.Entity.Diary", null)
                        .WithMany("Screenshot")
                        .HasForeignKey("DiaryID");
                });

            modelBuilder.Entity("DiaryOfTrader.Core.Entity.TraderSession", b =>
                {
                    b.HasOne("DiaryOfTrader.Core.Entity.TraderRegion", "Region")
                        .WithMany("Sessions")
                        .HasForeignKey("RegionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("SymbolTraderExchange", b =>
                {
                    b.HasOne("DiaryOfTrader.Core.Entity.TraderExchange", null)
                        .WithMany()
                        .HasForeignKey("ExchangesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaryOfTrader.Core.Entity.Symbol", null)
                        .WithMany()
                        .HasForeignKey("SymbolsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaryOfTrader.Core.Entity.Diary", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Screenshot");
                });

            modelBuilder.Entity("DiaryOfTrader.Core.Entity.MarketReview", b =>
                {
                    b.Navigation("Frames");
                });

            modelBuilder.Entity("DiaryOfTrader.Core.Entity.TraderRegion", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
