

namespace DiaryOfTrader.Core.Entity.Economic
{
  public class EconomicTimeOffset
  {
    private static List<EconomicTimeOffset> _list = new List<EconomicTimeOffset>()
    {
      new EconomicTimeOffset() { Code = "liTz2", Descrioption = "GMT -11:00) Midway Island" },
      new EconomicTimeOffset() { Code = "liTz35", Descrioption = "GMT -11:00) Samoa" },
      new EconomicTimeOffset() { Code = "liTz3", Descrioption = "GMT -10:00) Hawaii" },
      new EconomicTimeOffset() { Code = "liTz4", Descrioption = "GMT -8:00) Alaska" },
      new EconomicTimeOffset() { Code = "liTz37", Descrioption = "GMT -7:00) Arizona" },
      new EconomicTimeOffset() { Code = "liTz36", Descrioption = "GMT -7:00) Baja California" },
      new EconomicTimeOffset() { Code = "liTz38", Descrioption = "GMT -7:00) Chihuahua, La Paz, Mazatlan" },
      new EconomicTimeOffset() { Code = "liTz5", Descrioption = "GMT -7:00) Pacific Time (US &amp; Canada)" },
      new EconomicTimeOffset() { Code = "liTz40", Descrioption = "GMT -6:00) Guadalajara, Mexico City, Monterrey" },
      new EconomicTimeOffset() { Code = "liTz6", Descrioption = "GMT -6:00) Mountain Time (US &amp; Canada)" },
      new EconomicTimeOffset() { Code = "liTz42", Descrioption = "GMT -5:00) Bogota, Lima, Quito" },
      new EconomicTimeOffset() { Code = "liTz39", Descrioption = "GMT -5:00) Central America" },
      new EconomicTimeOffset() { Code = "liTz7", Descrioption = "GMT -5:00) Central Time (US &amp; Canada)" },
      new EconomicTimeOffset() { Code = "liTz41", Descrioption = "GMT -5:00) Saskatchewan" },
      new EconomicTimeOffset() { Code = "liTz44", Descrioption = "GMT -4:00) Asuncion" },
      new EconomicTimeOffset() { Code = "liTz9", Descrioption = "GMT -4:00) Caracas" },
      new EconomicTimeOffset() { Code = "liTz45", Descrioption = "GMT -4:00) Cuiaba" },
      new EconomicTimeOffset() { Code = "liTz8", Descrioption = "GMT -4:00) Eastern Time (US &amp; Canada)" },
      new EconomicTimeOffset() { Code = "liTz46", Descrioption = "GMT -4:00) Georgetown, La Paz, Manaus, San Juan" },
      new EconomicTimeOffset() { Code = "liTz43", Descrioption = "GMT -4:00) Indiana (East)" },
      new EconomicTimeOffset() { Code = "liTz47", Descrioption = "GMT -4:00) Santiago" },
      new EconomicTimeOffset() { Code = "liTz10", Descrioption = "GMT -3:00) Atlantic Time (Canada)" },
      new EconomicTimeOffset() { Code = "liTz12", Descrioption = "GMT -3:00) Brasilia" },
      new EconomicTimeOffset() { Code = "liTz48", Descrioption = "GMT -3:00) Buenos Aires" },
      new EconomicTimeOffset() { Code = "liTz49", Descrioption = "GMT -3:00) Cayenne, Fortaleza" },
      new EconomicTimeOffset() { Code = "liTz51", Descrioption = "GMT -3:00) Montevideo" },
      new EconomicTimeOffset() { Code = "liTz11", Descrioption = "GMT -2:30) Newfoundland" },
      new EconomicTimeOffset() { Code = "liTz50", Descrioption = "GMT -2:00) Greenland" },
      new EconomicTimeOffset() { Code = "liTz53", Descrioption = "GMT -1:00) Cape Verde Is." },
      new EconomicTimeOffset() { Code = "liTz14", Descrioption = "GMT) Azores" },
      new EconomicTimeOffset() { Code = "liTz55", Descrioption = "GMT) Coordinated Universal Time" },
      new EconomicTimeOffset() { Code = "liTz56", Descrioption = "GMT) Monrovia, Reykjavik" },
      new EconomicTimeOffset() { Code = "liTz54", Descrioption = "GMT +1:00) Casablanca" },
      new EconomicTimeOffset() { Code = "liTz15", Descrioption = "GMT +1:00) Dublin, Edinburgh, Lisbon, London" },
      new EconomicTimeOffset() { Code = "liTz166", Descrioption = "GMT +1:00) Lagos" },
      new EconomicTimeOffset() { Code = "liTz60", Descrioption = "GMT +1:00) West Central Africa" },
      new EconomicTimeOffset() { Code = "liTz16", Descrioption = "GMT +2:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna" },
      new EconomicTimeOffset() { Code = "liTz57", Descrioption = "GMT +2:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague" },
      new EconomicTimeOffset() { Code = "liTz58", Descrioption = "GMT +2:00) Brussels, Copenhagen, Madrid, Paris" },
      new EconomicTimeOffset() { Code = "liTz65", Descrioption = "GMT +2:00) Cairo" },
      new EconomicTimeOffset() { Code = "liTz67", Descrioption = "GMT +02:00) Johannesburg" },
      new EconomicTimeOffset() { Code = "liTz59", Descrioption = "GMT +2:00) Sarajevo, Skopje, Warsaw, Zagreb" },
      new EconomicTimeOffset() { Code = "liTz61", Descrioption = "GMT +2:00) Windhoek" },
      new EconomicTimeOffset() { Code = "liTz62", Descrioption = "GMT +3:00) Amman" },
      new EconomicTimeOffset() { Code = "liTz71", Descrioption = "GMT +3:00) Baghdad" },
      new EconomicTimeOffset() { Code = "liTz64", Descrioption = "GMT +3:00) Beirut" },
      new EconomicTimeOffset() { Code = "liTz66", Descrioption = "GMT +3:00) Damascus" },
      new EconomicTimeOffset() { Code = "liTz68", Descrioption = "GMT +3:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius" },
      new EconomicTimeOffset() { Code = "liTz63", Descrioption = "GMT +3:00) Istanbul" },
      new EconomicTimeOffset() { Code = "liTz17", Descrioption = "GMT +3:00) Jerusalem" },
      new EconomicTimeOffset() { Code = "liTz70", Descrioption = "GMT +3:00) Kuwait, Riyadh" },
      new EconomicTimeOffset() { Code = "liTz18", Descrioption = "GMT +3:00) Moscow, St. Petersburg, Volgograd" },
      new EconomicTimeOffset() { Code = "liTz72", Descrioption = "GMT +3:00) Nairobi" },
      new EconomicTimeOffset() { Code = "liTz19", Descrioption = "GMT +3:30) Tehran" },
      new EconomicTimeOffset() { Code = "liTz20", Descrioption = "GMT +4:00) Abu Dhabi, Dubai, Muscat" },
      new EconomicTimeOffset() { Code = "liTz73", Descrioption = "GMT +4:00) Baku" },
      new EconomicTimeOffset() { Code = "liTz21", Descrioption = "GMT +4:30) Kabul" },
      new EconomicTimeOffset() { Code = "liTz22", Descrioption = "GMT +5:00) Ekaterinburg" },
      new EconomicTimeOffset() { Code = "liTz77", Descrioption = "GMT +5:00) Karachi" },
      new EconomicTimeOffset() { Code = "liTz23", Descrioption = "GMT +5:30) Chennai, Kolkata, Mumbai, New Delhi" },
      new EconomicTimeOffset() { Code = "liTz79", Descrioption = "GMT +5:30) Colombo" },
      new EconomicTimeOffset() { Code = "liTz24", Descrioption = "GMT +5:45) Kathmandu" },
      new EconomicTimeOffset() { Code = "liTz25", Descrioption = "GMT +6:00) Dhaka" },
      new EconomicTimeOffset() { Code = "liTz26", Descrioption = "GMT +6:30) Yangon (Rangoon)" },
      new EconomicTimeOffset() { Code = "liTz27", Descrioption = "GMT +7:00) Bangkok, Hanoi, Jakarta" },
      new EconomicTimeOffset() { Code = "liTz28", Descrioption = "GMT +8:00) Beijing, Chongqing, Hong Kong, Urumqi" },
      new EconomicTimeOffset() { Code = "liTz178", Descrioption = "GMT +08:00) Manila" },
      new EconomicTimeOffset() { Code = "liTz113", Descrioption = "GMT +8:00) Singapore" },
      new EconomicTimeOffset() { Code = "liTz29", Descrioption = "GMT +9:00) Osaka, Sapporo, Tokyo" },
      new EconomicTimeOffset() { Code = "liTz88", Descrioption = "GMT +9:00) Seoul" },
      new EconomicTimeOffset() { Code = "liTz30", Descrioption = "GMT +9:30) Adelaide" },
      new EconomicTimeOffset() { Code = "liTz91", Descrioption = "GMT +10:00) Brisbane" },
      new EconomicTimeOffset() { Code = "liTz31", Descrioption = "GMT +10:00) Canberra, Melbourne, Sydney" },
      new EconomicTimeOffset() { Code = "liTz94", Descrioption = "GMT +10:00) Vladivostok" },
      new EconomicTimeOffset() { Code = "liTz32", Descrioption = "GMT +11:00) Solomon Is., New Caledonia" },
      new EconomicTimeOffset() { Code = "liTz33", Descrioption = "GMT +12:00) Auckland, Wellington" },
      new EconomicTimeOffset() { Code = "liTz1", Descrioption = "GMT +12:00) Eniwetok, Kwajalein" }
    };
    public string Code { get; set; }
    public string Descrioption { get; set; }
    public static IReadOnlyCollection<EconomicTimeOffset> TimeOffsets { get { return _list.AsReadOnly(); } }
  }
}
